# Generated by Django 2.2.24 on 2021-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('annual_income', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('N', None), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
